name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: |
          echo "::group::Info"
          echo "Commit Msg: '${{github.event.head_commit.message}}'"
          echo "Actor: ${{github.actor}}"
          echo "Event Name: ${{github.event_name}}"
          echo "Event Path: ${{github.event_path}}"
          echo "HEAD Ref: ${{github.head_ref}}"
          echo "Ref Name: ${{github.ref_name}}"
          echo "Ref Type: ${{github.ref_type}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Workspace: ${{github.workspace}}"
          echo "Action: ${{github.action}}"
          echo "Action Path: ${{github.action_path}}"
          echo "Action Ref: ${{github.action_ref}}"
          echo "Action Status: ${{github.action_status}}"
          echo "Repo: ${{github.action_repository}}"
          echo "Base Ref: ${{github.base_ref}}"
          echo "ENV: ${{ toJSON(env) }}"
          echo "Job: ${{ toJSON(job) }}"
          echo "Steps: ${{ toJSON(steps) }}"
          echo "Runner: ${{ toJSON(runner) }}"
          echo "OS: ${RUNNER_OS}"
          echo "::endgroup::"
          echo "::notice:: ${{github.actor}} has triggered CI"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup
        run: npm i -g pnpm @antfu/ni
      - name: Clean Install
        run: nci
      - name: Lint
        run: nr lint --if-present
      - name: Cancel Workflow
        if: failure()
        uses: andymckay/cancel-action@0.4
