/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for GitHub Actions step definitions
 */
export type GitHubActionsStepSchema = {
  /**
   * A unique identifier for the step
   */
  id?: string;
  /**
   * Conditional expression to determine if the step should run
   */
  if?: string;
  /**
   * Display name for the step
   */
  name?: string;
  /**
   * Action to use for the step
   */
  uses?: string;
  /**
   * Command to run
   */
  run?: string;
  /**
   * Working directory for the step
   */
  "working-directory"?: string;
  /**
   * Shell to use for the run command
   */
  shell?: "bash" | "pwsh" | "python" | "sh" | "cmd" | "powershell";
  /**
   * Input parameters for the action
   */
  with?: {
    [k: string]: string | number | boolean;
  };
  /**
   * Environment variables for the step
   */
  env?: {
    [k: string]: string;
  };
  /**
   * Allow the workflow to continue even if this step fails
   */
  "continue-on-error"?: boolean;
  /**
   * Maximum number of minutes to run the step
   */
  "timeout-minutes"?: number;
} & {
  [k: string]: unknown;
};
