name: Multi Job Workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "Job 2"
