name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

jobs:
  on_push:
    name: on_push
    uses: yankeeinlondon/gha/.github/workflows/on_push.yml@main
    secrets:
      api_token: ${{secrets.API_TOKEN}}
      gh_token: ${{secrets.GH_TOKEN}}
      bitbucket_token: ${{secrets.BITBUCKET_TOKEN}}
      gitlab_token: ${{secrets.GITLAB_TOKEN}}
