name: CI (features)

on:
  push:
    branches:
      - feature/*

  pull_request:
    branches:
      - main
      - master

jobs:
  testing:
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
