name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    name: test
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main

  publish:
    name: npm
    if: ( contains(github.event.head_commit.message, 'release v') )
    needs:
      - test
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
    with:
      nodeVersion: 16
    secrets:
      npm_token: ${{secrets.NPM_TOKEN}}

  do_not_publish:
    name: npm / no publication
    if: ( !contains(github.event.head_commit.message, 'release v') )
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Done
        run: |
          echo "no publication to NPM required"
