name: On Push

on:
  push:
    branches:
      - main
jobs:
  test:
    name: testing
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
    # Example: To test only on Linux with Node 20.x, uncomment below:
    # with:
    #   os: 'ubuntu-latest'
    #   nodeVersion: '20.x'

  publish:    
    name: publish
    if: contains(github.event.head_commit.message, 'release v')
    needs: test  # This ensures tests pass before publishing
    uses: yankeeinlondon/gha/.github/workflows/publish.yml@main
    # Example: To use different package names per platform, uncomment below:
    # with:
    #   jsr_scope: '@yankeeinlondon'
    #   github_packages_scope: '@yankeeinlondon'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

