name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: testing
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
    secrets:
      gh_token: ${{secrets.GH_TOKEN}}

  publish:
    name: publish
    uses: yankeeinlondon/gha/.github/workflows/publish.yml@main
    needs:
        - test
    secrets:
      gh_token: ${{secrets.GH_TOKEN}}
