name: NPM Publish

on:
  workflow_call:
    inputs:
      nodeVersion:
        type: number
        default: 16
        required: false
      private:
        type: boolean
        default: false
        required: false

    secrets:
      npm_token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: https://registry.npmjs.org/
      - name: Install pnpm
        run: npm i -g pnpm @antfu/ni
      - name: Clean Install
        run: nci
      - name: Build
        run: nr build
      - name: Info
        run: |
          echo "user:\t\t${{github.actor}}"
          echo "commit msg:\t\t${{github.eventType}}"
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Create Changelog Entry
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
