name: Test Only

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: testing
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
    secrets:
      gh_token: ${{secrets.GH_TOKEN}}
