name: Test

on:
  workflow_call:

jobs:
  lint:
    name: test / lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup
        run: npm i -g pnpm @antfu/ni
      - name: Clean Install
        run: nci
      - name: Lint
        run: nr lint --if-present

  unit:
    name: test / unit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: npm i -g pnpm @antfu/ni
      - name: Clean Install
        run: nci
      - name: Build
        run: nr build
      - name: Test
        run: nr test --if-present

  complete:
    name: test / complete
    runs-on: ubuntu-latest
    needs:
      - test
      - lint

    steps:
      - name: Success
        run: |
          echo :rocket: tests run successfully
