name: Test

on:
  workflow_call:
    inputs:
      os:
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
        required: false
      nodeVersions:
        type: string
        default: '["14.x", "16.x"]'
        required: false
      failFast:
        type: boolean
        default: false
        required: false

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup
        run: npm i -g pnpm @antfu/ni
      - name: Clean Install
        run: nci
      - name: Lint
        run: nr lint --if-present

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.nodeVersions) }}
        os: ${{ fromJSON(inputs.os) }}
      fail-fast: false
      # fail-fast: ${{ inputs.failFast }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: npm i -g pnpm @antfu/ni
      - name: Install
        # https://github.com/antfu/ni#nci---clean-install
        run: nci
      - name: Build
        run: nr build
      - name: Test
        run: nr test --if-present

  complete:
    name: complete
    runs-on: ubuntu-latest
    needs:
      - test
      - lint

    steps:
      - name: Success
        run: |
          echo ":rocket: tests run successfully"
          echo "::notice status=success::Tests and Linting completed successfully"
